blank_issues_enabled: false
contact_links:
  - name: Have questions or need support?
    url: https://forum.iobroker.net/category/6/skripten-logik
    about: Please get in touch on the ioBroker Community Forum!